name: Main CI
on: [push, pull_request]
env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.BRANCH_NAME }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9

      - name: Setup node environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"
          cache-dependency-path: "web/pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm i --frozen-lockfile
        working-directory: web

      - name: Try build
        run: pnpm build
        env:
          CI: true
